### ISSUE TITLE
triggerObservers() skips all other observers when currentObserver is found?

### ISSUE THREAD

**Issue by danielweck** [tomasklaen/statin#2]
Shouldn't this be `continue;`, not `return;`?

https://github.com/tomasklaen/statin/blob/d9d35e3def67b60a663a3afc4d6f2ab8f8b9c5ff/src/index.ts#L176-L177

**Comment by tomasklaen** [comment]
Yes, for correctness, this should definitely be `continue` instead of `return`.

In practice, after an hour of trying to write a failing test for it, I've realized that the current observer is always going to be last on the observers set, and that's why this has never caused any issues.

It's still an error that could potentially cause some in future, and wouldn't be caught without a code review until then, so thank you a lot for going out of your way and spending your time reviewing a library used by 1 person in the world! :)
